apiVersion: v1
kind: Service
metadata:
 name: k8s_fastapi
spec:
 type: LoadBalancer
 selector:
   app: k8s_fastapi
 ports:
 - port: 8000
   targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: k8s_fastapi
spec:
 replicas: 1
 selector:
   matchLabels:
     app: k8s_fastapi
 template:
   metadata:
     labels:
       app: k8s_fastapi
   spec:
     containers:
     - name: k8s_fastapi
       image: rejebchaalia/k8s_fastapi
       resources:
         limits:
           memory: "128Mi"
           cpu: "128m"
       ports:
       - containerPort: 8000